### ISSUE TITLE
Could we use this from a libray / dll ?

### ISSUE THREAD

**Issue by ignatandrei** [DamianEdwards/RazorSlices#18]
Could we use this from a libray / dll ?

**Comment by DamianEdwards** [comment]
Not yet. I intend to support using this from a [Razor Class Library](https://learn.microsoft.com/aspnet/core/razor-pages/ui-class), in addition to it being usable from a [class library targeting ASP.NET Core](https://learn.microsoft.com/aspnet/core/fundamentals/target-aspnetcore), but I [haven't added the functionality required to find slices from referenced libraries](https://github.com/DamianEdwards/RazorSlices/blob/main/src/RazorSlices/RazorSlice.ResolveAndCreate.cs#L17) just yet. Note it will still depend on ASP.NET Core.

**Comment by ignatandrei** [comment]
Ok. I will close for now. Let's see in 1 year ;-)
