### ISSUE TITLE
Make _slicesByName lookup case in-sensitive

### ISSUE THREAD

**Issue by jchannon** [DamianEdwards/RazorSlices#24]
If I have a Slices/Test.cshtml and I want to dynamically look up views by path for example having a route /test will not find the view.

For example:

```
        var path = req.Path.ToString();
        var viewName = path == "/" ? "Index.cshtml" : $"{path}.cshtml";

        var result = Results.Extensions.RazorSlice($"/Slices{viewName}", model);
```

**Comment by DamianEdwards** [comment]
@jchannon to be clear, you want slice lookup to be case **insensitive**, yes?
