### ISSUE TITLE
Support @inject to enable declaring dependency-injected properties

### ISSUE THREAD

**Issue by DamianEdwards** [DamianEdwards/RazorSlices#3]
Needs a few things:

- Discover properties on the slice classes that were created via `@inject` directives (they'll be decorated with `[RazorInject]`)
  - Note that by default a bunch of MVC-related properties are auto-injected to all generated classes which we'd need to exclude from the discovered properties:
    ```csharp
    [RazorInject]
	public IModelExpressionProvider ModelExpressionProvider { get; private set; } = null;


	[RazorInject]
	public IUrlHelper Url { get; private set; } = null;


	[RazorInject]
	public IViewComponentHelper Component { get; private set; } = null;


	[RazorInject]
	public IJsonHelper Json { get; private set; } = null;


	[RazorInject]
	public IHtmlHelper<dynamic> Html { get; private set; } = null;
    ```
- Update the render methods to support accepting an `IServiceProvider` to resolve injected property values from
- Add logic that initializes the property values from the `IServiceProvider` when the slice instance is created

**Comment by madeyoga** [comment]
Hi Damian, I'd be happy to contribute to this issue. Is it still open for contributions?

**Comment by DamianEdwards** [comment]
Certainly! Some extra implementation thoughts about this one:

- The details of injectable properties on slices should be stored as part of slice discovery. I knew I'd need to overhaul slice definition discovery to store more details about slices (e.g. support for layout will need this too) so this is a good time to do that. I'm thinking we'd add a `SliceDefinition` type that has all the relevant details on it and is the item stored in the two dictionaries (one keyed by `string` identifier, the other keyed by `Type` sliceType).
-  We'll want the `IServiceProvider` to be accepted as a parameter to a new kind of `SliceFactory` for slices that have injectable properties, this would mean the `ResovleSliceFactory` methods would need new overloads to accept the `IServiceProvider` and throw if the slice has injectable properties and an `IServiceProvider` wasn't provided, and of course the generated expression-based `delegate` will now need to set all the injectable properties. The `IServiceProvider` needs to be passed in when the slice is created per request so that scoped services can be correctly resolved.
- The render methods will need overloads that accept an `IServiceProvider` and the overload that doesn't accept an `IServiceProvider` will need to throw if the sliced resolved for the path has injectable properties (although that might be taken care of by `ResolveSliceFactory` throwing as talked about above).
- The `IResult`-related methods will also need to account for slices with injectable properties and support accepting an `IServiceProvider` too.
