### ISSUE TITLE
Will this project support native AOT?

### ISSUE THREAD

**Issue by albertwoo** [DamianEdwards/RazorSlices#31]
Now dotnet 8 already support minimal api with AOT, it this project can also support that, it would be very cool.

**Comment by DamianEdwards** [comment]
I'd love for it to support native AOT! The types the Razor compiler currently generates from .cshtml files are "unspeakables" which complicates matters a bit but the type names **are** deterministic so it might be possible to make it work. I chatted with @davidfowl about it and we have a few ideas to experiment with.

**Comment by DamianEdwards** [comment]
I proved out that I can support native AOT in the aot branch. I need to now write a source generator to complete the story. Some notes/links to help:

- https://github.com/dotnet/roslyn/blob/main/docs/features/incremental-generators.md#authoring-a-cache-friendly-generator
- [JsonSourceGenerator](https://github.com/dotnet/runtime/blob/3e960d90b1d1bc80f0c3890a237e526d01dca84b/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Roslyn4.0.cs#L25-L55)
- [RegexGenerator](https://github.com/dotnet/runtime/blob/3e960d90b1d1bc80f0c3890a237e526d01dca84b/src/libraries/System.Text.RegularExpressions/gen/RegexGenerator.cs#L41-L131)
- [LibraryImportGenerator](https://github.com/dotnet/runtime/blob/1ff48ad53e01d1db3b5ad6b247347dc5609cb93a/src/libraries/System.Runtime.InteropServices/gen/LibraryImportGenerator/LibraryImportGenerator.cs#L39-L106)
