### ISSUE TITLE
AddRazorRuntimeCompilation

### ISSUE THREAD

**Issue by sovantha** [DamianEdwards/RazorSlices#39]
Just wondering if runtime compilation option can be enabled or not?

**Comment by DamianEdwards** [comment]
I have no plans to enable it. Runtime compilation requires the app to reference the full C# compiler toolchain (aka Roslyn) and wouldn't support trimming or native AOT (which I plan to support).

**Comment by sovantha** [comment]
Understand that. Thank you.
