### ISSUE TITLE
Using RazorSlices in library project

### ISSUE THREAD

**Issue by jtsom** [DamianEdwards/RazorSlices#51]
I have an app that has a separate service library that I need to generate some html. I have the nuget package installed into the project, with the /Slices directory with my .cshtml files and the appropriate _ViewImports.cshtml file(s). After updating to the new version and trying to make the adjustments for the new code, the "slices" don't seem to get generated from the source generator. (I have enabled the output into the /obj directory with `<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>` in the .csproj, but I don't see any "Generated" files - so I cannot create any slices. 

My .cshtml uses partials to pull in several other files, and those were all causing errors. I was previously using 
`RenderPartialAsync("/Slices/_partial.cshtml", model)`
but an trying to use the new strongly types classes but the new classes aren't found, as the generated files aren't found. Neither are the "top level" files.

My Slices looks like:
![image](https://github.com/DamianEdwards/RazorSlices/assets/13488/6dc29b43-0dcc-46fa-9578-6f0f252586f2)

**Comment by DamianEdwards** [comment]
The sample app in the repo includes a Razor class library, as do the benchmark projects, so it's not that it doesn't work at all. I'll need more information to narrow down what's going on here. Can you share an isolated project that reproduces the issue?

**Comment by DamianEdwards** [comment]
Also note it seems common that the editor doesn't see the generated types and shows errors, but the project builds just fine.

**Comment by jtsom** [comment]
I'll try to get some sample - this is an internal app I'm trying to update.

In the simple sample app that I attached to another issue has the generated files in the `obj` directory, so the source generators are running:
![image](https://github.com/DamianEdwards/RazorSlices/assets/13488/f0c4cf66-4fa8-4ac7-8221-e0ac08e10c2d)

but in this other solution, the `obj` directory does not have any of the files that would come from the "slices":

![image](https://github.com/DamianEdwards/RazorSlices/assets/13488/981bae40-0bb1-4049-88b6-98093b0825ae)

**Comment by jtsom** [comment]
I just found this in the solution explorer: 
![image](https://github.com/DamianEdwards/RazorSlices/assets/13488/79b177c7-d068-46e7-8e78-eea33318ebea)

**Comment by jtsom** [comment]
Here is a sample that attempts to use RazorSlices in a library project. The source generator does not run so the generated files are not there, so cannot create the html.

[Net8Test.zip](https://github.com/user-attachments/files/15778955/Net8Test.zip)

**Comment by DamianEdwards** [comment]
Your project Net8Test.Service is not using the Razor SDK and thus isn't a Razor Class Library. Once I changed the project file to the following it worked:

```csproj
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

<ItemGroup>
    <PackageReference Include="RazorSlices" Version="0.8.1" />
</ItemGroup>

</Project>
```

Would be good to add a diagnostic to the Razor Slices source generator that emits a warning if this is detected so it's easier to diagnose.

**Comment by jtsom** [comment]
Yep. That fixes the source generation. But I'm getting this error on build - 

![image](https://github.com/DamianEdwards/RazorSlices/assets/13488/0843c9be-42e0-44b7-8865-d2c072d90ad3)

**Comment by jtsom** [comment]
One step forward...

I can't seem to create the Slice - the generated class isn't found:

![image](https://github.com/DamianEdwards/RazorSlices/assets/13488/5fbd9073-fd7a-41d3-9094-464d1ee03acf)

I'd expect to see a "Slices.Hello" in there? and looking at the generated file, I would assume it would be?

![image](https://github.com/DamianEdwards/RazorSlices/assets/13488/2fb772e4-51be-4f3c-bb95-cb0dcee2b7a5)

**Comment by jtsom** [comment]
Again. Nevermind. Closing the solution and reopen it got Visual Studio to wake up.

**Comment by jtsom** [comment]
Now.
![image](https://github.com/DamianEdwards/RazorSlices/assets/13488/a9185f0b-5897-4331-a0dc-d9ed57883061)

**Comment by DamianEdwards** [comment]
You need to import the `RazorSlices` namespace to get the extension methods that return a `string`:

```csharp
using RazorSlices;

namespace Net8Test.Service;

public class TestService
{
    public async ValueTask<string> Generate(string c)
    {
        var t = new MyTestClass()
        {
            Url = c
        };
        
        var x = Slices.Hello.Create(t);

        var r = await x.RenderAsync();

        return r;
    }
}

public class MyTestClass
{
    public string Url { get; set; } = null!;
}
```

**Comment by DamianEdwards** [comment]
Closing this and tracking the analyzer idea via #66
