### ISSUE TITLE
how to pass IServiceProvider to RenderPartialAsync

### ISSUE THREAD

**Issue by ivanjx** [DamianEdwards/RazorSlices#53]
i have a partial cshtml that needs to use `@inject`. im not sure on how to pass the service provider to that partial cshtml. on the parent cshtml, i do this in the c#:
```cs
var slice = RegistrationActivation.Create<RegistrationActivationModel>(
    new(language, name, link));
slice.ServiceProvider = _serviceProvider;
```

and this is what i do in the cshtml to generate the partial:
```razor
@(await RenderPartialAsync<RegistrationActivationButton, RegistrationActivationButtonModel>(
        new(Model.Language, Model.Link)))
```

**Comment by DamianEdwards** [comment]
It should just work. Are you seeing an error? Can you put together a minimal repro project and share it?

**Comment by ivanjx** [comment]
ah ok if it should just work. it was just a question. i will report it back if i encounter any issues.
