### ISSUE TITLE
Best Way (any way) to Render from string/path

### ISSUE THREAD

**Issue by tbasallo** [DamianEdwards/RazorSlices#55]
I've been using the library to get the HTML. I'd pass the path to the slice and a model to a method and return the HTML (for the body of an email). The methods s looked like (this is part of a bigger library):
```
public async Task<string> GetHtml<T>(string pathToView, T model)
{
     var html = await (RazorSlice.Create(pathToView, model)).RenderAsync();
     return html;
}
```
The changes seem to indicate that the only way to do it now is:
```
var razorSlice = MyProject.Slices.MyCoolView.Create(model);
```
But you have to know the type a compile time. It seems there's no longer an option of a string to find the slice. What's the best way to do the same with the changes If we don't know the type at compile time? Maybe I missed an extension method or other method.

Perhaps Activator.Create or some way using something like GetHtml<TSlice, TModel>(....) but I haven't figured that one out yet. 

Is there a prescribed way to do this?

**Comment by DamianEdwards** [comment]
The new version went wholesale on source generators and optimizing to support trimming and native AOT. As such, the old approach was completely replaced by the new approach. That said, I could introduce a new way to get a slice instance via its path by code generating a type/method with a big switch statement in it that news up and returns the relevant slice instance for the path passed.

I just need to decide the API shape as there isn't a natural place to generate such an API too. The usual approach for this type of thing in the world of source generators is to make users declare a `partial` class (that may or may not derive from a base class depending on the needs of the generated code) and is decorated with some marker attribute and then have the source generator generate the other part of that partial. The advantage of this approach is that it leaves the issue of what to call and where to put this class (from an assembly, namespace, visibility, and name point of view) to the consumer.

So, imagine something like this in your project:

```csharp
namespace MyApp;

// You can name this class whatever you like
[RazorSliceFactory]
public static partial class SliceFactory { }
```

Would end up with something like the following being generated by the Razor Slices generator:

```csharp
namespace MyApp;

public static partial class SliceFactory
{
    public static bool TryCreateSlice(string path, [NotNullWhen(true)] out RazorSlice? slice)
    {
        slice = CreateSliceImpl(path);
        return slice != null;
    }

    public static bool TryCreateSlice<TModel>(string path, TModel model, [NotNullWhen(true)] out RazorSlice<TModel>? slice)
    {
        slice = CreateSliceImpl(path, model);
        return slice != null;
    }

    public static RazorSlice CreateSlice(string path)
    {
        return CreateSliceImpl(path) ?? throw new SliceNotFoundException($"Razor Slice with path '{path}' could not be found.");
    }

    public static RazorSlice<TModel> CreateSlice<TModel>(string path, TModel model)
    {
        return CreateSliceImpl(path, model) ?? throw new SliceNotFoundException($"Razor Slice with path '{path}' and model type {typeof(TModel)} could not be found.");
    }

    public static IEnumerable<string> AllSlicePaths { get;} = ["/Foo.cshtml"];

    private static RazorSlice<TModel>? CreateSliceImpl<TModel>(string path, TModel? model = null)
    {
        // TODO: Need to figure out case-sensitivity, leading slash, etc.
        return path switch
        {
            "/Foo.cshtml" => model is FooModel m ? MyApp.Slices.Foo.Create(m) : null,
            "/Bar.cshtml" => model is null ? MyApp.Slices.Bar.Create() : null,
            "/Foo/Bar/Index.cshtml" => model is IndexModel m ? MyApp.Slices.Foo.Bar.Index.Create(m) : null,
            _ => null
        };
    }
}
```

Then you could use it like this in your original example:

```csharp
public async Task<string> GetHtml<T>(string pathToView, T model)
{
     var html = await (MyApp.SliceFactory.CreateSlice(pathToView, model)).RenderAsync();
     return html;
}
```

**Comment by tbasallo** [comment]
That makes a lot of sense and so does the proposal. At the same time, I wonder if it's better to get away from magic strings altogether (the paths).

Since the views are inheriting from RazorSlice or RazorSliceHttpResult anyway, perhaps that gets passed in to the library and take it from there, or just get the html outside of the library and send in the generated HTML. This also allows for better compile time safety.

I think the time is better spent on other features since this just takes a change of how one thinks about these things. I'm going to close this as not needed, unless you feel it's worth tracking.
