### ISSUE TITLE
How do I use the "Razor Slices source generator"?

### ISSUE THREAD

**Issue by LAC-Tech** [DamianEdwards/RazorSlices#58]
Hello, I have a question from the docs:

`Each .cshtml file will have a proxy type generated for it by the Razor Slices source generator that you can use as the generic argument to the various APIs in Razor Slices for rendering slices.`

I assume I have to invoke this source generator somehow?

**Comment by DamianEdwards** [comment]
No, source generators are automatically invoked by the compiler. As long as you're in a supporting environment, e.g. Visual Studio, VS Code with C# Dev Kit, etc., and you reference the `RazorSlices` package and have some *.cshtml* files in your project, you should see the generated types become available in your IntelliSense/statement-completion, e.g.:

![image](https://github.com/user-attachments/assets/90223f9c-9059-4f2a-a7bb-b37d981fc64b)

Note that it can take a few seconds for it all to initialize before the generated types show up.
