### ISSUE TITLE
Generator emmits invalid code for Create.cshtml

### ISSUE THREAD

**Issue by timker** [DamianEdwards/RazorSlices#59]
I have an existing Razor Pages project that already has several Create.cshtml (not slices, just standard razor pages)
This is causing many  compiler errors with the source generated files

## offending code
```
    public sealed class Create : global::RazorSlices.IRazorSliceProxy
{
...
      public static global::RazorSlices.RazorSlice Create()
```
## error
Error (active)	CS0542	'Create': member names cannot be the same as their enclosing type

It would be great if this clash could be removed.

Note to anyone else
```
	  <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles> 
```
will allow you to review the generated c#

**Comment by DamianEdwards** [comment]
Yep right now Razor Slices doesn't play well in projects that have non-Razor Slices *.cshtml* files. This is covered by #63 I think.

**Comment by timker** [comment]
could we Just skip Create, because I'm assuming a Create RazorSlice would never work

**Comment by timker** [comment]
actually i read the docs, 

and skipping Pages and Areas is a great solution

```
<PropertyGroup>
  <EnableDefaultRazorSlices>false</EnableDefaultRazorSlices>
</PropertyGroup>
<ItemGroup>
  <!-- Only treat .cshtml files in Slices directory as Razor Slices -->
  <RazorSlice Include="Slices\**\*.cshtml" Exclude="Slices\**\_Layout.cshtml;Slices\**\_ViewImports.cshtml" />
</ItemGroup>
```
