### ISSUE TITLE
Consider wrapping PipeWriter/IBufferWriter to amortize GetSpan+Advance

### ISSUE THREAD

**Issue by BrennanConroy** [DamianEdwards/RazorSlices#61]
For some reason Linux seems to be affected by many GetSpan+Advance calls (haven't noticed any issues on Windows). A solution is to wrap the `IBufferWriter` (same concept for PipeWriter probably works) and store the `GetSpan` call until more memory is needed and only then call `Advance`.

See https://github.com/aspnet/Benchmarks/compare/50b1bda1fa826a4ec10cb13940f47c9de09a7b98...a4c8bb152c1da1364dae38c45ec60ce70b0914eb as an example when I was attempting to update the Fortunes benchmark.

**Comment by DamianEdwards** [comment]
This is already handled in the latest version.
