### ISSUE TITLE
Limit directories that Generator proxies classes

### ISSUE THREAD

**Issue by tbasallo** [DamianEdwards/RazorSlices#63]
Currently if you add RazorSlices to a project every CSHTML file will be proxied. This causes some issues with existing classes. 

This can be solved by using an RCL, but then model management becomes a pain.

Is there a way to limit RazorSlices to only proxy classes/files inside a given directory (for example, /Slices). This would allow to continue to use existing models and minimize issues with existing code.

**Comment by DamianEdwards** [comment]
Currently there isn't, but that's a good idea.

The most likely approach would be to flow this info from the project file/MSBuild. Right now, the source generator just grabs all *.cshtml* files (that aren't *_ViewImports.cshtml* or *_ViewStart.cshtml*):

https://github.com/DamianEdwards/RazorSlices/blob/1181bf81a26f50eda23e56ea4ece870268ee913f/src/RazorSlices.SourceGenerator/RazorSliceProxyGenerator.cs#L29-L32

This logic could potentially be changed to instead get *.cshtml* file paths from the project metadata set by targets that this library would import and run after the core Razor compiler targets, which already creates items for each *.cshtml* file to be input for generation (i.e. [`RazorGenerate` items](https://github.com/dotnet/sdk/blob/4bd57604aad52e0133f88c30118f0e0fbe03300e/src/RazorSdk/Targets/Sdk.Razor.CurrentVersion.targets#L527-L530)). So this library's targets could define a new item type, e.g. `<RazorSlice />`, which by default would be populated with all `<RazorGenerate />` items from the core targets, but then could be modified in the project file to include or exclude whatever you like, e.g.:

```xml
<PropertyGroup>
  <DisableRazorSliceDefaultItems>true</DisableRazorSliceDefaultItems>
</PropertyGroup>
<ItemGroup>
  <RazorSlice Include="/slices/**/*.cshtml" />
</ItemGroup>
```

**Comment by DamianEdwards** [comment]
The fix for this is now available in https://github.com/DamianEdwards/RazorSlices/releases/tag/v0.9.0

To exclude *.cshtml* files from being treated as Razor Slices, add the following to your *.csproj* file and edit accordingly:

```xml
<ItemGroup>
  <!-- Don't treat .cshtml files in Views or Pages directory as Razor Slices -->
  <RazorSliceGenerate Include="Views\**\*.cshtml;Pages\**\*.cshtml" GenerateRazorSlice="false" />
</ItemGroup>
```
