### ISSUE TITLE
Razor Slices doesn't play well with Results<T0, T1> pattern

### ISSUE THREAD

**Issue by naasking** [DamianEdwards/RazorSlices#64]
I want to define an endpoint that I can ensure only returns either a razor slice or a redirect. In ASP.NET I would normally do something like this:

    public static Results<IRazorSliceHttpResult, RedirectHttpResult> Hello() =>
        Results.Extensions.RazorSlice<MyApp.Slices.Hello, Model>(new Mode());

However, [Results<T0, T1>](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpresults.results-2) constructs instances *only* via an implicit user-defined conversion. Since Results.Extensions.RazorSlice returns an interface and [user-defined implicit conversions do not work on interfaces in C#](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/conversions#1052-permitted-user-defined-conversions), this pattern appears to be literally impossible with Razor Slices at the moment.

It could be made compatible by changing Results.Extensions.RazorSlice to return a non-interface type. If RazorSliceHttpResultWrapper could inherit from RazorSliceHttpResult, then that would work as the return type.

**Comment by naasking** [comment]
To workaround this I basically had to replicate the RazorSliceHttpResultWrapper and all of the supporting logic into a custom wrapper type.

**Comment by DamianEdwards** [comment]
Thanks for the report. The goal is to ensure unnecessary allocations are avoided, so always returning `RazorSliceHttpResultWrapper` is undesirable as it involves allocating a new wrapper object every request. I'll need to revisit the `IResult` extensions to see if there's a way to alter the type shape/hierarchy to fit this need but I seem to recall some forces pushing me to introduce the interface.

**Comment by DamianEdwards** [comment]
This fix is now available in https://github.com/DamianEdwards/RazorSlices/releases/tag/v0.9.0

**Comment by naasking** [comment]
Thanks, that works but with a minor wrinkle. I can't declare an endpoint like this, that ensures either an HTML result or a 404:

```c#
    public static Results<RazorSliceHttpResult, NotFound> Endpoint()
    {
        ...
        if (foo)
            return Results.Extensions.RazorSlice<Slices.Other, Foo>(
               new Foo { ... });
        ...
        return Results.Extensions.RazorSlice<Slices.Another, Bar>(
           new Bar { ... });
    }
```

I'm forced to declare it like this:

```c#
    public static Results<RazorSliceHttpResult<Foo>, RazorSliceHttpResult<Bar>, NotFound> Drawings()
    {
        ...
    }
```
Ultimately this seems like it's due to the typed version being unrelated to the untyped version by inheritance, and this might be why you had an interface here before. That would have worked if only C# supported implicit conversions on interfaces.

I can see a couple of possible solutions here if you want to include something out of the box for this case.

# Restructure RazorSlice

Move the HTTP result logic into the base `RazorSlice` type, and then all endpoints can just return `RazorSlice`. That extra logic is just ignored if it's not used in that context. However, this would impose a dependency on the ASP.NET package which may not be desirable.

# Wrapper

A wrapper solves all of these issues, but I understand you wish to minimize allocations. However, it can be made a struct, so if using `Result<T0,T1,...>`, it incurs no allocation in principle, unless ASP.NET internally boxes it at some point. If endpoints return IResult types, then the old interface or the current approach would be fine, but when using typed results `IResultExtensions` gets a new method to return this struct wrapper, or the end user has to manually construct it as I do below. Below I've included the wrapper I had been using which aggregated the code you wrote into one type. The endpoints using this could be declared like the first version:

```c#
    public static Results<HtmlResult, NotFound> Endpoint()
    {
        ...
        if (foo)
            return new HtmlResult(Slices.Other.Create(new Foo { ... }));
        ...
        return new HtmlResult(Slices.Another.Create(new Bar { ... }));
    }
```

Here is the struct wrapper:

```C#
    // copied from: https://github.com/DamianEdwards/RazorSlices/blob/main/src/RazorSlices/RazorSliceHttpResultWrapper.cs
    public struct HtmlResult(RazorSlice razorSlice) : IRazorSliceHttpResult, IDisposable
    {
        public int? StatusCode { get; set; } = StatusCodes.Status200OK;

        int? IStatusCodeHttpResult.StatusCode => StatusCode;

        public string ContentType => "text/html; charset=utf-8";

        public HtmlEncoder? HtmlEncoder { get; set; }

        /// <inheritdoc />
        Task IResult.ExecuteAsync(HttpContext httpContext)
        {
            razorSlice.HttpContext = httpContext;
            return ExecuteAsync(razorSlice, httpContext, HtmlEncoder, StatusCode ?? StatusCodes.Status200OK, ContentType);
        }

        internal static Task ExecuteAsync(RazorSlice slice, HttpContext httpContext, HtmlEncoder? htmlEncoder, int statusCode, string contentType)
        {
            ArgumentNullException.ThrowIfNull(httpContext);

            // The HtmlEncoder property can be set on the instance to avoid the overhead of RequestServices if desired
            var effectiveHtmlEncoder = htmlEncoder ?? httpContext.RequestServices.GetService<HtmlEncoder>();

            httpContext.Response.StatusCode = statusCode;
            httpContext.Response.ContentType = contentType;

            // Force the response to start before rendering the slice
            var startTask = httpContext.Response.StartAsync();

            if (!startTask.IsCompletedSuccessfully)
            {
                // Go async
                return AwaitStartTaskAndRender(startTask, slice, httpContext, effectiveHtmlEncoder);
            }

#pragma warning disable CA2012 // Use ValueTasks correctly: The ValueTask is observed in code below
            var renderTask = slice.RenderAsync(httpContext.Response.BodyWriter, effectiveHtmlEncoder, httpContext.RequestAborted);
#pragma warning restore CA2012

            if (!HandleSynchronousCompletion(renderTask))
            {
                // Go async
                return AwaitRenderTaskAndFlushResponse(renderTask, httpContext.Response.BodyWriter, httpContext.RequestAborted);
            }

            return GetAsTask(httpContext.Response.BodyWriter.FlushAsync(httpContext.RequestAborted));
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static bool HandleSynchronousCompletion(ValueTask task)
        {
            if (task.IsCompletedSuccessfully)
            {
                task.GetAwaiter().GetResult();
                return true;
            }
            return false;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static Task GetAsTask(ValueTask<FlushResult> valueTask)
        {
            // Try to avoid the allocation from AsTask
            if (valueTask.IsCompletedSuccessfully)
            {
                // Signal consumption to the IValueTaskSource
                var _ = valueTask.GetAwaiter().GetResult();
                return Task.CompletedTask;
            }
            else
            {
                return valueTask.AsTask();
            }
        }

        private static async Task AwaitStartTaskAndRender(Task startTask, RazorSlice slice, HttpContext httpContext, HtmlEncoder? htmlEncoder)
        {
            await startTask;
            await slice.RenderAsync(httpContext.Response.BodyWriter, htmlEncoder, httpContext.RequestAborted);
            await httpContext.Response.BodyWriter.FlushAsync(httpContext.RequestAborted);
        }

        private static async Task AwaitRenderTaskAndFlushResponse(ValueTask renderTask, PipeWriter responseBodyWriter, CancellationToken cancellationToken)
        {
            await renderTask;
            await responseBodyWriter.FlushAsync(cancellationToken);
        }

        public void Dispose()
        {
            razorSlice.Dispose();
        }
    }
```

**Comment by DamianEdwards** [comment]
> Move the HTTP result logic into the base RazorSlice type, and then all endpoints can just return RazorSlice. 

This is what I've been considering after the ergonomic wrinkles with this change became apparent post-shipping. The library already depends on ASP.NET Core and that can't realistically be removed anyway so it wouldn't impose any extra dependency.

**Comment by DamianEdwards** [comment]
Opened #84 to track
